import React from 'react';

export function Faqs() {
  return (
    <div className="faqs-page min-h-screen bg-[#e0f5f7] py-10 px-4">
      <div className="rd-mailform text-left w-full max-w-6xl mx-auto bg-white border border-gray-200 rounded-md shadow-md p-6 md:p-8">
        <h5 className="text-center text-xl font-bold" style={{color:'#01a2a6'}}>FREQUENTLY ASKED QUESTIONS</h5>
        <hr className="divider bg-madison hr-sm-left-0" />
        <br />
        
        <div className="faq-content">
          <div style={{marginBottom: '24px'}}>
            <p className="western" style={{marginBottom: '8px'}}>
              <strong>Q1. Can all types of bus passes be made online?</strong>
            </p>
            <p className="western" style={{marginLeft: '0.5in', marginRight: '0.5in', textIndent: '-0.5in', marginBottom: '0px'}}>
              <span style={{color: '#000000'}}>Ans. Yes, All type of bus passes i.e. Conventional Bus Pass (Printed Ticket Type) and e-Bus Pass can be made online.</span>
            </p>
          </div>

          <div style={{marginBottom: '24px'}}>
            <p className="western" style={{marginBottom: '8px'}}>
              <strong>Q2. What is the difference between e-Bus Pass and Conventional Bus Pass?</strong>
            </p>
            <p className="western" style={{marginLeft: '0.5in', marginRight: '0.5in', textIndent: '-0.5in', marginBottom: '0px'}}>
              <span style={{color: '#000000'}}>
                Ans. <u>e-Bus Pass</u><br />
                e-Bus Pass is a bus pass generated dynamically by the system and can be viewed by clicking the link delivered through SMS on the Applicant Mobile Number.
                <br /><u>Conventional Bus Pass:</u><br />
                Conventional Bus Pass is a Printed Ticket Type bus pass generated by the system and is delivered at the applicant residence through Speed Post.
              </span>
            </p>
          </div>

          <div style={{marginBottom: '32px'}}>
            <p className="western" style={{marginBottom: '12px'}}>
              <strong>Q3. What types of bus passes can be made online and what are their charges per month?</strong>
            </p>
            <p className="western" style={{marginLeft: '0.5in', marginRight: '0.5in', textIndent: '-0.5in', marginBottom: '12px'}}>
              <span style={{color: '#000000'}}>Ans. All types of bus passes i.e. Conventional Bus Pass as well as e-Bus Pass can be made online as per following monthly charges:</span>
            </p>

            <h6 style={{color: '#000000', marginLeft: '0.5in', textIndent: '-0.5in', marginBottom: '12px'}}>
              <u>General Bus Passes</u>
            </h6>

          <div className="table-responsive">
            <table className="table table-bordered" style={{width: '100%', maxWidth: '800px'}}>
              <thead>
                <tr>
                  <th style={{border: '1px solid #00000a', padding: '8px'}}>S.No</th>
                  <th style={{border: '1px solid #00000a', padding: '8px'}}>Type of Bus Pass</th>
                  <th style={{border: '1px solid #00000a', padding: '8px'}}>Monthly Charge</th>
                  <th style={{border: '1px solid #00000a', padding: '8px'}}>Quarterly Charge</th>
                  <th style={{border: '1px solid #00000a', padding: '8px'}}>Half-Yearly Charge</th>
                  <th style={{border: '1px solid #00000a', padding: '8px'}}>Yearly Charge</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td style={{border: '1px solid #00000a', padding: '8px'}}>1</td>
                  <td style={{border: '1px solid #00000a', padding: '8px'}}>General all route Non-AC bus</td>
                  <td style={{border: '1px solid #00000a', padding: '8px'}}>Rs.800/-</td>
                  <td style={{border: '1px solid #00000a', padding: '8px'}}>Rs.2280/-</td>
                  <td style={{border: '1px solid #00000a', padding: '8px'}}>Rs.4440/-</td>
                  <td style={{border: '1px solid #00000a', padding: '8px'}}>Rs.8640/-</td>
                </tr>
                <tr>
                  <td style={{border: '1px solid #00000a', padding: '8px'}}>2</td>
                  <td style={{border: '1px solid #00000a', padding: '8px'}}>General all route AC bus</td>
                  <td style={{border: '1px solid #00000a', padding: '8px'}}>Rs.1000/-</td>
                  <td style={{border: '1px solid #00000a', padding: '8px'}}>Rs.2850/-</td>
                  <td style={{border: '1px solid #00000a', padding: '8px'}}>Rs.5550/-</td>
                  <td style={{border: '1px solid #00000a', padding: '8px'}}>Rs.10800/-</td>
                </tr>
                <tr>
                  <td style={{border: '1px solid #00000a', padding: '8px'}}>3</td>
                  <td style={{border: '1px solid #00000a', padding: '8px'}}>Airport Express/Coaches AC and Non AC bus (in NCT of Delhi Only)</td>
                  <td style={{border: '1px solid #00000a', padding: '8px'}}>Rs.1400/-</td>
                  <td style={{border: '1px solid #00000a', padding: '8px'}}>NA</td>
                  <td style={{border: '1px solid #00000a', padding: '8px'}}>NA</td>
                  <td style={{border: '1px solid #00000a', padding: '8px'}}>NA</td>
                </tr>
                <tr>
                  <td style={{border: '1px solid #00000a', padding: '8px'}}>4</td>
                  <td style={{border: '1px solid #00000a', padding: '8px'}}>Delhi-NCR-Airport AC and Non AC bus</td>
                  <td style={{border: '1px solid #00000a', padding: '8px'}}>Rs.1800/-</td>
                  <td style={{border: '1px solid #00000a', padding: '8px'}}>NA</td>
                  <td style={{border: '1px solid #00000a', padding: '8px'}}>NA</td>
                  <td style={{border: '1px solid #00000a', padding: '8px'}}>NA</td>
                </tr>
                <tr>
                  <td style={{border: '1px solid #00000a', padding: '8px'}}>5</td>
                  <td style={{border: '1px solid #00000a', padding: '8px'}}>Delhi to Gurgaon</td>
                  <td style={{border: '1px solid #00000a', padding: '8px'}}>Rs.1500/-</td>
                  <td style={{border: '1px solid #00000a', padding: '8px'}}>NA</td>
                  <td style={{border: '1px solid #00000a', padding: '8px'}}>NA</td>
                  <td style={{border: '1px solid #00000a', padding: '8px'}}>NA</td>
                </tr>
                <tr>
                  <td style={{border: '1px solid #00000a', padding: '8px'}}>6</td>
                  <td style={{border: '1px solid #00000a', padding: '8px'}}>Delhi to Faridabad</td>
                  <td style={{border: '1px solid #00000a', padding: '8px'}}>Rs.1800/-</td>
                  <td style={{border: '1px solid #00000a', padding: '8px'}}>NA</td>
                  <td style={{border: '1px solid #00000a', padding: '8px'}}>NA</td>
                  <td style={{border: '1px solid #00000a', padding: '8px'}}>NA</td>
                </tr>
                <tr>
                  <td style={{border: '1px solid #00000a', padding: '8px'}}>7</td>
                  <td style={{border: '1px solid #00000a', padding: '8px'}}>Delhi to Bahadurgarh</td>
                  <td style={{border: '1px solid #00000a', padding: '8px'}}>Rs.1160/-</td>
                  <td style={{border: '1px solid #00000a', padding: '8px'}}>NA</td>
                  <td style={{border: '1px solid #00000a', padding: '8px'}}>NA</td>
                  <td style={{border: '1px solid #00000a', padding: '8px'}}>NA</td>
                </tr>
                <tr>
                  <td style={{border: '1px solid #00000a', padding: '8px'}}>8</td>
                  <td style={{border: '1px solid #00000a', padding: '8px'}}>Delhi to Ghaziabad</td>
                  <td style={{border: '1px solid #00000a', padding: '8px'}}>Rs.1640/-</td>
                  <td style={{border: '1px solid #00000a', padding: '8px'}}>NA</td>
                  <td style={{border: '1px solid #00000a', padding: '8px'}}>NA</td>
                  <td style={{border: '1px solid #00000a', padding: '8px'}}>NA</td>
                </tr>
              </tbody>
            </table>
          </div>

          <h6 style={{color: '#000000', marginLeft: '0.5in', textIndent: '-0.5in', marginTop: '20px'}}>
            <u>Concessional Bus Passes</u>
          </h6>

          <div className="table-responsive">
            <table className="table table-bordered" style={{width: '100%', maxWidth: '800px'}}>
              <thead>
                <tr>
                  <th style={{border: '1px solid #00000a', padding: '8px'}}>S.No</th>
                  <th style={{border: '1px solid #00000a', padding: '8px'}}>Type of Bus Pass</th>
                  <th style={{border: '1px solid #00000a', padding: '8px'}}>Monthly Charge</th>
                  <th style={{border: '1px solid #00000a', padding: '8px'}}>Quarterly Charge</th>
                  <th style={{border: '1px solid #00000a', padding: '8px'}}>Half-Yearly Charge</th>
                  <th style={{border: '1px solid #00000a', padding: '8px'}}>Yearly Charge</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td style={{border: '1px solid #00000a', padding: '8px'}}>1</td>
                  <td style={{border: '1px solid #00000a', padding: '8px'}}>Student Destination Pass</td>
                  <td style={{border: '1px solid #00000a', padding: '8px'}}>Rs.100/-</td>
                  <td style={{border: '1px solid #00000a', padding: '8px'}}>Rs.300/-</td>
                  <td style={{border: '1px solid #00000a', padding: '8px'}}>--</td>
                  <td style={{border: '1px solid #00000a', padding: '8px'}}>--</td>
                </tr>
                <tr>
                  <td style={{border: '1px solid #00000a', padding: '8px'}}>2</td>
                  <td style={{border: '1px solid #00000a', padding: '8px'}}>Student All Route Special Pass</td>
                  <td style={{border: '1px solid #00000a', padding: '8px'}}>Rs.150/-</td>
                  <td style={{border: '1px solid #00000a', padding: '8px'}}>Rs.450/-</td>
                  <td style={{border: '1px solid #00000a', padding: '8px'}}>--</td>
                  <td style={{border: '1px solid #00000a', padding: '8px'}}>--</td>
                </tr>
                <tr>
                  <td style={{border: '1px solid #00000a', padding: '8px'}}>3</td>
                  <td style={{border: '1px solid #00000a', padding: '8px'}}>Senior Citizens Above 60 Years (AC Pass)</td>
                  <td style={{border: '1px solid #00000a', padding: '8px'}}>Rs.150/-</td>
                  <td style={{border: '1px solid #00000a', padding: '8px'}}>Rs.450/-</td>
                  <td style={{border: '1px solid #00000a', padding: '8px'}}>Rs.900/-</td>
                  <td style={{border: '1px solid #00000a', padding: '8px'}}>Rs.1800/-</td>
                </tr>
                <tr>
                  <td style={{border: '1px solid #00000a', padding: '8px'}}>4</td>
                  <td style={{border: '1px solid #00000a', padding: '8px'}}>Senior Citizens Above 60 Years (Non-AC Pass)</td>
                  <td style={{border: '1px solid #00000a', padding: '8px'}}>Rs.50/-</td>
                  <td style={{border: '1px solid #00000a', padding: '8px'}}>Rs.150/-</td>
                  <td style={{border: '1px solid #00000a', padding: '8px'}}>Rs.300/-</td>
                  <td style={{border: '1px solid #00000a', padding: '8px'}}>Rs.600/-</td>
                </tr>
                <tr>
                  <td style={{border: '1px solid #00000a', padding: '8px'}}>5</td>
                  <td style={{border: '1px solid #00000a', padding: '8px'}}>Divyangjan (All Categories)</td>
                  <td style={{border: '1px solid #00000a', padding: '8px'}}>--</td>
                  <td style={{border: '1px solid #00000a', padding: '8px'}}>--</td>
                  <td style={{border: '1px solid #00000a', padding: '8px'}}>--</td>
                  <td style={{border: '1px solid #00000a', padding: '8px'}}>Free</td>
                </tr>
                <tr>
                  <td style={{border: '1px solid #00000a', padding: '8px'}}>6</td>
                  <td style={{border: '1px solid #00000a', padding: '8px'}}>Freedom Fighters & War Widows</td>
                  <td style={{border: '1px solid #00000a', padding: '8px'}}>--</td>
                  <td style={{border: '1px solid #00000a', padding: '8px'}}>--</td>
                  <td style={{border: '1px solid #00000a', padding: '8px'}}>--</td>
                  <td style={{border: '1px solid #00000a', padding: '8px'}}>Free</td>
                </tr>
              </tbody>
            </table>
          </div>
          </div>

          <div className="additional-faqs" style={{marginTop: '40px'}}>
            <div style={{marginBottom: '24px'}}>
              <p style={{marginBottom: '8px'}}><strong>Q4. What additional charges for buying online bus pass?</strong></p>
              <p style={{marginBottom: '8px'}}>Ans. Apart from the above charges, the following charges will be applicable:</p>
            <ul>
              <li>Any Bank Charges charged by bank for each online transaction should be borne by customer.</li>
              <li>Printing and stationary charges of Rs. 15/- for each pass.</li>
              <li>Speed Post charges of Rs 18/- for local area and Rs 41/- for non-local area pin codes.</li>
              <li>For e-Bus Pass there are no additional charges except bank transaction charges.</li>
            </ul>
            </div>

            <div style={{marginBottom: '24px'}}>
              <p style={{marginBottom: '8px'}}><strong>Q5. Can bus passes be still made offline at DTC pass sections?</strong></p>
              <p style={{marginBottom: '0px'}}>Ans. Yes, applicant can also buy all types bus passes through offline procedure at any DTC pass section.</p>
            </div>

            <div style={{marginBottom: '24px'}}>
              <p style={{marginBottom: '8px'}}><strong>Q6. Can I renew my offline bus pass online?</strong></p>
              <p style={{marginBottom: '0px'}}>Ans. No, user cannot renew any bus pass online.</p>
            </div>

            <div style={{marginBottom: '24px'}}>
              <p style={{marginBottom: '8px'}}><strong>Q7. Can I use the bus pass as an ID card?</strong></p>
              <p style={{marginBottom: '0px'}}>Ans. No, bus pass can only be used for travelling purposes in DTC & Cluster buses only.</p>
            </div>

            <div style={{marginBottom: '24px'}}>
              <p style={{marginBottom: '8px'}}><strong>Q8. What is the minimum age to apply for a bus pass?</strong></p>
              <p style={{marginBottom: '0px'}}>Ans. Above 5 years.</p>
            </div>

            <div style={{marginBottom: '24px'}}>
              <p style={{marginBottom: '8px'}}><strong>Q9. Where and How to contact?</strong></p>
              <p style={{marginBottom: '0px'}}>
                <strong>Address:</strong> Pass Section, Delhi Transport Corporation,<br />
                Scindia House, KG Marg, Connaught Place, New Delhi 110001<br /><br />
                <strong>Phone:</strong> 011-23737180, 011-23752770 Ext.226<br />
                <strong>Mobile:</strong> 8744073213
              </p>
            </div>

            <div style={{marginBottom: '24px'}}>
              <p style={{marginBottom: '8px'}}><strong>Q10. How do I track my bus pass?</strong></p>
              <p style={{marginBottom: '0px'}}>Ans. You will receive a consignment number via SMS. Track at: 
                <a href="https://www.indiapost.gov.in/_layouts/15/dop.portal.tracking/trackconsignment.aspx" target="_blank" rel="noopener noreferrer">
                  India Post Tracking
                </a>
              </p>
            </div>

            <div style={{marginBottom: '24px'}}>
              <p style={{marginBottom: '8px'}}><strong>Q11. In how much time will I receive the bus pass?</strong></p>
              <p style={{marginBottom: '0px'}}>Ans. The applicant will receive the bus pass within 5 working days excluding date of transaction of payment.</p>
            </div>

            <div style={{marginBottom: '24px'}}>
              <p style={{marginBottom: '8px'}}><strong>Q12. Can I personally collect my bus pass from the DTC office?</strong></p>
              <p style={{marginBottom: '0px'}}>Ans. No, However in case the postal authorities return the bus pass due to incorrect address or other delivery issues, applicant can collect the bus passes from the pass section, DTC Scindia House, KG Marg Connaught Place, New Delhi, Delhi – 110001 between 10:00 AM to 4:00 PM on all working days.</p>
            </div>

            <div style={{marginBottom: '24px'}}>
              <p style={{marginBottom: '8px'}}><strong>Q13. Can I change the applicant details or edit the form after submitting the online form?</strong></p>
              <p style={{marginBottom: '0px'}}>Ans. No, you cannot edit form details after final submission. In case of rejection of application due to incomplete address or blurred photo, you will be given an option to change address and photo only.</p>
            </div>

            <div style={{marginBottom: '24px'}}>
              <p style={{marginBottom: '8px'}}><strong>Q14. To which areas are the Bus Pass delivery services available? What are the delivery charges?</strong></p>
              <p style={{marginBottom: '0px'}}>Ans. The delivery services are available all over India. Postal delivery charges would be applicable as per actual charges levied by India Post.</p>
            </div>

            <div style={{marginBottom: '24px'}}>
              <p style={{marginBottom: '8px'}}><strong>Q15. In how much time will I receive the bus pass?</strong></p>
              <p style={{marginBottom: '0px'}}>Ans. The applicant will receive the bus pass within 5 working days excluding date of transaction of payment.</p>
            </div>

            <div style={{marginBottom: '24px'}}>
              <p style={{marginBottom: '8px'}}><strong>Q16. Will bus pass be redispatched in case of return by Postal Authority?</strong></p>
              <p style={{marginBottom: '0px'}}>Ans. No, pass will not be redispatched if it could not be delivered by India Post due to any of the aforesaid reasons. In this scenario, the applicant have to collect his/her pass from DTC pass section.</p>
            </div>

            <div style={{marginBottom: '24px'}}>
              <p style={{marginBottom: '8px'}}><strong>Q17. What is the process for cancellation of the bus pass?</strong></p>
              <p style={{marginBottom: '0px'}}>Ans. To cancel your bus pass, you will have to visit the DTC pass section with original bus pass and valid ID proof. Cancellation charges will be applicable as per DTC rules.</p>
            </div>

            <div style={{marginBottom: '24px'}}>
              <p style={{marginBottom: '8px'}}><strong>Q18. What are cancellation charges of a bus pass?</strong></p>
              <p style={{marginBottom: '0px'}}>Ans. Cancellation charges vary based on the type of pass and duration. Please contact DTC pass section for specific details.</p>
            </div>

            <div style={{marginBottom: '24px'}}>
              <p style={{marginBottom: '8px'}}><strong>Q19. What are the Refund rules?</strong></p>
              <p style={{marginBottom: '8px'}}>Ans. Refund rules are as follows:</p>
              <ul style={{marginBottom: '0px'}}>
                <li>Monthly Pass: If cancelled within first 10 days, 75% refund will be given</li>
                <li>Quarterly Pass: If cancelled within first month, proportionate refund will be given</li>
                <li>Half-yearly/Yearly Pass: Refund will be calculated proportionately based on unused period</li>
                <li>No refund for e-Bus Pass</li>
              </ul>
            </div>

            <div style={{marginBottom: '24px'}}>
              <p style={{marginBottom: '8px'}}><strong>Q20. In how much time will I receive the refund after cancellation of bus pass?</strong></p>
              <p style={{marginBottom: '0px'}}>Ans. Refund will be processed within 15-20 working days after cancellation and verification.</p>
            </div>

            <div style={{marginBottom: '24px'}}>
              <p style={{marginBottom: '8px'}}><strong>Q21. What should I do in case of lost/damaged bus pass?</strong></p>
              <p style={{marginBottom: '0px'}}>Ans. In case of lost/damaged bus pass, no duplicate pass will be issued. Applicant will have to apply for a fresh bus pass.</p>
            </div>

            <div style={{marginBottom: '24px'}}>
              <p style={{marginBottom: '8px'}}><strong>Q22. How to get e-Bus Pass, in case SMS or Email containing Link is deleted?</strong></p>
              <p style={{marginBottom: '0px'}}>Ans. Visit URL: <a href="http://dtcpass.delhi.gov.in/" target="_blank" rel="noopener noreferrer">http://dtcpass.delhi.gov.in/</a> and use the "Re-generate E-Pass" option with your application details.</p>
            </div>

            <h6 style={{color: '#000000', marginTop: '30px', textAlign: 'center'}}>
              <u><strong>Documents Required for Concessional Bus Pass</strong></u><br />
              <u>Table No. II</u>
            </h6>

            <div className="table-responsive" style={{marginTop: '20px'}}>
              <table className="table table-bordered" style={{width: '100%'}}>
                <thead>
                  <tr>
                    <th style={{border: '1px solid #00000a', padding: '8px', backgroundColor: '#f8f9fa', textAlign: 'center'}}>S.No</th>
                    <th style={{border: '1px solid #00000a', padding: '8px', backgroundColor: '#f8f9fa', textAlign: 'center'}}>Category</th>
                    <th style={{border: '1px solid #00000a', padding: '8px', backgroundColor: '#f8f9fa', textAlign: 'center'}}>Eligibility</th>
                    <th style={{border: '1px solid #00000a', padding: '8px', backgroundColor: '#f8f9fa', textAlign: 'center'}}>Documents Required</th>
                    <th style={{border: '1px solid #00000a', padding: '8px', backgroundColor: '#f8f9fa', textAlign: 'center'}}>Remarks</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td style={{border: '1px solid #00000a', padding: '8px', textAlign: 'center'}}>1</td>
                    <td style={{border: '1px solid #00000a', padding: '8px'}}>Student Concessional Pass<br />(Destination Pass & All Route Pass)</td>
                    <td style={{border: '1px solid #00000a', padding: '8px'}}>Students of recognized schools/colleges/universities up to Post Graduate level</td>
                    <td style={{border: '1px solid #00000a', padding: '8px'}}>• School/College ID Card<br />• Fee Receipt of current academic year<br />• Bonafide Certificate from Principal/Director<br />• Age proof (if required)</td>
                    <td style={{border: '1px solid #00000a', padding: '8px'}}>Valid only during academic session. Renewal required every year.</td>
                  </tr>
                  <tr>
                    <td style={{border: '1px solid #00000a', padding: '8px', textAlign: 'center'}}>2</td>
                    <td style={{border: '1px solid #00000a', padding: '8px'}}>Press Pass<br />(AC & Non-AC)</td>
                    <td style={{border: '1px solid #00000a', padding: '8px'}}>Accredited Press correspondents and photographers</td>
                    <td style={{border: '1px solid #00000a', padding: '8px'}}>• Press accreditation card issued by Govt. of India/Delhi<br />• Letter from newspaper/media organization<br />• Identity proof</td>
                    <td style={{border: '1px solid #00000a', padding: '8px'}}>Must be renewed annually with fresh accreditation</td>
                  </tr>
                  <tr>
                    <td style={{border: '1px solid #00000a', padding: '8px', textAlign: 'center'}}>3</td>
                    <td style={{border: '1px solid #00000a', padding: '8px'}}>Senior Citizens Pass<br />(Above 60 years)</td>
                    <td style={{border: '1px solid #00000a', padding: '8px'}}>Male citizens above 60 years and Female citizens above 58 years</td>
                    <td style={{border: '1px solid #00000a', padding: '8px'}}>• Age proof: Birth Certificate/10th Certificate/Passport/Driving License/Voter ID/Aadhaar Card<br />• Address proof<br />• Identity proof</td>
                    <td style={{border: '1px solid #00000a', padding: '8px'}}>Age verification is mandatory. Only one pass per person.</td>
                  </tr>
                  <tr>
                    <td style={{border: '1px solid #00000a', padding: '8px', textAlign: 'center'}}>4</td>
                    <td style={{border: '1px solid #00000a', padding: '8px'}}>PRS/AAY Pass<br />(Priority/Antyodaya families)</td>
                    <td style={{border: '1px solid #00000a', padding: '8px'}}>Members of Priority Household (PRS) and Antyodaya Anna Yojana (AAY) families</td>
                    <td style={{border: '1px solid #00000a', padding: '8px'}}>• Valid PRS/AAY Ration Card<br />• Address proof matching ration card<br />• Identity proof of applicant<br />• Family member proof (if applicable)</td>
                    <td style={{border: '1px solid #00000a', padding: '8px'}}>Only for registered family members. Ration card must be active.</td>
                  </tr>
                  <tr>
                    <td style={{border: '1px solid #00000a', padding: '8px', textAlign: 'center'}}>5</td>
                    <td style={{border: '1px solid #00000a', padding: '8px'}}>Divyangjan Pass<br />(Persons with Disabilities)</td>
                    <td style={{border: '1px solid #00000a', padding: '8px'}}>Persons with disabilities:<br />• Blind<br />• Orthopedic (40% & above)<br />• Deaf & Dumb (60 dB & above)<br />• Mental Illness<br />• Locomotor disability</td>
                    <td style={{border: '1px solid #00000a', padding: '8px'}}>• Disability Certificate (40% or above) issued by competent medical authority<br />• Identity proof<br />• Address proof<br />• For blind persons: one attendant certificate (if applicable)</td>
                    <td style={{border: '1px solid #00000a', padding: '8px'}}>Free pass. Medical certificate must be from recognized hospital/authority. Attendant allowed for blind persons.</td>
                  </tr>
                  <tr>
                    <td style={{border: '1px solid #00000a', padding: '8px', textAlign: 'center'}}>6</td>
                    <td style={{border: '1px solid #00000a', padding: '8px'}}>Freedom Fighter Pass<br />(with one attendant)</td>
                    <td style={{border: '1px solid #00000a', padding: '8px'}}>Recognized Freedom Fighters and their spouses</td>
                    <td style={{border: '1px solid #00000a', padding: '8px'}}>• Freedom Fighter Certificate issued by Central/State Government<br />• Identity proof<br />• Address proof<br />• Attendant's identity proof and relationship certificate</td>
                    <td style={{border: '1px solid #00000a', padding: '8px'}}>Free pass for one year. One attendant allowed. Certificate must be government-issued.</td>
                  </tr>
                  <tr>
                    <td style={{border: '1px solid #00000a', padding: '8px', textAlign: 'center'}}>7</td>
                    <td style={{border: '1px solid #00000a', padding: '8px'}}>International Sportsmen Pass</td>
                    <td style={{border: '1px solid #00000a', padding: '8px'}}>Sportspersons who have represented India at International level</td>
                    <td style={{border: '1px solid #00000a', padding: '8px'}}>• Certificate from Sports Authority of India<br />• Certificate from National Sports Federation<br />• Proof of International participation<br />• Identity proof</td>
                    <td style={{border: '1px solid #00000a', padding: '8px'}}>Free pass for one year. Valid for recognized international competitions only.</td>
                  </tr>
                  <tr>
                    <td style={{border: '1px solid #00000a', padding: '8px', textAlign: 'center'}}>8</td>
                    <td style={{border: '1px solid #00000a', padding: '8px'}}>National Award Winners Pass</td>
                    <td style={{border: '1px solid #00000a', padding: '8px'}}>Recipients of National Awards in various fields (Arts, Literature, Sports, etc.)</td>
                    <td style={{border: '1px solid #00000a', padding: '8px'}}>• Original National Award Certificate<br />• Government endorsement letter<br />• Identity proof<br />• Address proof</td>
                    <td style={{border: '1px solid #00000a', padding: '8px'}}>Free pass for six months. Award must be recognized by Government of India.</td>
                  </tr>
                  <tr>
                    <td style={{border: '1px solid #00000a', padding: '8px', textAlign: 'center'}}>9</td>
                    <td style={{border: '1px solid #00000a', padding: '8px'}}>War Widows Pass<br />(& Their Dependents)</td>
                    <td style={{border: '1px solid #00000a', padding: '8px'}}>Widows of Armed Forces personnel who died in action and their dependents</td>
                    <td style={{border: '1px solid #00000a', padding: '8px'}}>• War Widow Certificate from Armed Forces<br />• Death Certificate of spouse (showing death in action)<br />• Identity proof<br />• Dependent relationship proof (for dependents)</td>
                    <td style={{border: '1px solid #00000a', padding: '8px'}}>Free pass for six months. Can be extended. Includes dependent children under 21 years.</td>
                  </tr>
                  <tr>
                    <td style={{border: '1px solid #00000a', padding: '8px', textAlign: 'center'}}>10</td>
                    <td style={{border: '1px solid #00000a', padding: '8px'}}>MLA/MP Attendant Pass<br />(AC/Non-AC)</td>
                    <td style={{border: '1px solid #00000a', padding: '8px'}}>Attendants/Personal Staff of MLAs and MPs</td>
                    <td style={{border: '1px solid #00000a', padding: '8px'}}>• Official letter from MLA/MP office<br />• Employment certificate/ID card<br />• Attendant's identity proof<br />• Address proof</td>
                    <td style={{border: '1px solid #00000a', padding: '8px'}}>Free pass for one year. Valid only during tenure of MLA/MP. Limited to specified attendants only.</td>
                  </tr>
                </tbody>
              </table>
            </div>

            <div style={{textAlign: 'center', marginTop: '40px', paddingTop: '20px', borderTop: '2px solid #01a2a6'}}>
              <p style={{color: '#666', fontSize: '14px'}}>------------------------o---------------------------</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default Faqs;
